name: Deploy AWS 

on: 
  push:
    branches:
      - main 
    paths:
      - 'lambda/**'

jobs:
  deploy-lambda: # Sets or specifies the runner 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python  # Setups our python env 
      uses: actions/setup-python@v2
      with: 
        python-version: '3.13'

    - name: Install Dependencies # Installs any packages
      run: 
        python -m pip install --upgrade pip 
        pip install -r lambda/requirements.txt -t lambda/ 

    - name: Configure AWS Creds  # Sets up AWS Creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Lambda Function #Zips Lamba directory and updates lamda function
      run: |
        cd lambda 
        zip -r lambda.zip .
        aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lamba.zip 